name: Manually trigger workflow
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag to update Dockerfile with'
        required: true
        default: 'latest'
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'prd'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo "Hello, world!  ${{ github.event.inputs.environment }}"